version: '3.5'

services:
  php:
    container_name: ${APP_NAME}-php-apache-container
    image: mitlabs/apache-php7.4
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
    links:
      - mysql:db

  mysql:
    image: mysql:5.7.36
    container_name: ${APP_NAME}-mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - LANG=C.UTF-8  # this one should be added
      - TZ=Asia/Tashkent
    volumes:
      - ${DB_DATA_PATH}:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    command: --character-set-server=utf8 --collation-server=utf8_general_ci

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin-container
    links:
      - mysql:db
    ports:
      - "8765:80"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
